spring:
  datasource:
    url:jdbc:oracle:thin:@127.0.0.1:1521:channel
    username:channel
    password:channel
    driver-class-name:oracle.jdbc.driver.OracleDriver
    max-idle:10
    max-wait:10000
    min-idle:5
    initial-size:5
#Mybatis
mybatis:
  config-location: classpath:config/mybatis/mybatis-config.xml
  mapper-locations: classpath:config/mybatis/mapper/*Mapper.xml
  type-aliases-package: bros.manage.business.mapper