spring: 
  datasource:
    type: com.mchange.v2.c3p0.ComboPooledDataSource
#c3p0数据源配置，需要放开DatasourceConfiguration.java的config注解
c3p0: 
  jdbcUrl: jdbc:db2://192.168.241.3:50001/provider
  user: db2inst1
  password: db2inst1
  driverClass: com.ibm.db2.jcc.DB2Driver
  minPoolSize: 5
  maxPoolSize: 10
  maxIdleTime: 1800000
  acquireIncrement: 3
  maxStatements: 1000
  initialPoolSize: 3
  idleConnectionTestPeriod: 60
  acquireRetryAttempts: 30
  acquireRetryDelay: 1000
  breakAfterAcquireFailure: false
  testConnectionOnCheckout: false
  
#Mybatis
mybatis:
  config-location: classpath:config/mybatis/mybatis-config.xml
  mapper-locations: classpath:config/mybatis/mapper/*Mapper.xml
  type-aliases-package: bros.manage.business.mapper
#logback日志文件路径
logging:
  config: classpath:logbak-spring.xml
logback: 
  #logdir: /Users/inke/dev/log/tomcat/sell
  logdir: D:\springbootlog
  appname: manage
  #分割日志文件大小
  filesize: 50 MB
  #日志文件级别：受rootLevel控制，需要保持一致，不一致按rootLevel级别
  fileLevel: DEBUG
  consoleLevel: DEBUG
  rootLevel: DEBUG